import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      return (saved as Language) || 'en';
    }
    return 'en';
  });

  const isRTL = language === 'ar';

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translations
const translations: Record<Language, Record<string, any>> = {
  en: {
    nav: {
      home: 'Home',
      about: 'About',
      categories: 'Categories',
      partnerships: 'Partnerships',
      gala: 'Gala',
      contact: 'Contact',
      nominate: 'Nominate',
      submitNomination: 'Submit Nomination',
    },
    hero: {
      title: 'ONE UAE',
      titleAccent: 'Awards',
      tagline: 'International Business Awards',
      patronage: 'Under the Patronage of H.E. Sheikh Sultan Bin Nasser Bin Humaid Al Nuaimi',
      date: 'February 5, 2026',
      venue: 'Zabeel Ladies Club, Dubai',
      submitNomination: 'Submit Nomination',
      learnMore: 'Learn More',
      addToCalendar: 'Add to Calendar',
    },
    stats: {
      guests: 'Distinguished Guests',
      categories: 'Award Categories',
      dignitaries: 'VIP Dignitaries',
      night: 'Prestigious Night',
    },
    about: {
      label: 'About the Awards',
      title: 'A National Platform for Excellence',
      description: 'The ONE UAE International Business Awards is a prestigious national platform honoring individuals and establishments driving the UAE\'s journey of growth, development, and sustainability.',
      date: 'February 5, 2026',
      galaLabel: 'Gala Night Ceremony',
      venueTitle: 'Zabeel Ladies Club',
      venueDetail: 'Main Ballroom, Dubai',
      discoverStory: 'Discover Our Story',
      intro: 'What began as a vision to honor outstanding contributions has grown into a platform celebrating the diverse achievements that define the UAE\'s spirit of unity, vision, and excellence.',
      awardCategories: 'Award Categories',
      distinguishedGuests: 'Distinguished Guests',
      mission: 'Mission',
      missionText: 'To recognize leaders and institutions contributing to national progress and UAE Vision 2071.',
      vision: 'Vision',
      visionText: 'To build a prestigious tradition of honoring excellence, unity, and sustainable advancement.',
      underPatronage: 'Under the Patronage',
      patronName: 'H.E. Sheikh Sultan Bin Nasser Bin Humaid Al Nuaimi',
      patronDesc: 'ONE UAE International Business Awards is honored to operate under the distinguished patronage of H.E. Sheikh Sultan Bin Nasser Bin Humaid Al Nuaimi, whose commitment to excellence and national development continues to inspire our mission.',
      theJourney: 'The Journey',
      selectionProcess: 'Selection Process',
      step1Title: 'Nomination',
      step1Desc: 'Individuals and organizations submit nominations highlighting exceptional achievements.',
      step2Title: 'Expert Review',
      step2Desc: 'A distinguished panel evaluates nominations based on impact and innovation.',
      step3Title: 'Final Selection',
      step3Desc: 'Winners are selected and honored at our prestigious annual ceremony.',
      submitYourNomination: 'Submit Your Nomination',
    },
    categories: {
      label: '18 Categories',
      title: 'Award Categories',
      viewAll: 'View All',
      more: '+ 12 more categories',
      recognition: 'Recognition',
      categoriesOfExcellence: 'Categories of Excellence',
      readyToApply: 'Ready to Apply?',
      submitYourNomination: 'Submit Your Nomination',
      recognizeExcellence: 'Recognize excellence in your organization or nominate a deserving leader.',
      startNomination: 'Start Nomination',
      growth: 'Growth',
      development: 'Development',
      sustainability: 'Sustainability',
      list: [
        'Growth & Economic Excellence',
        'Entrepreneurship & Innovation',
        'Corporate Leadership',
        'Finance & Banking',
        'Retail & Hospitality',
        'Technology & Digital',
      ],
      fullList: [
        { title: 'Growth & Economic Excellence', pillar: 'Growth' },
        { title: 'Entrepreneurship & Innovation', pillar: 'Growth' },
        { title: 'Corporate Leadership', pillar: 'Growth' },
        { title: 'Finance & Banking', pillar: 'Growth' },
        { title: 'Retail & Hospitality', pillar: 'Growth' },
        { title: 'Technology & Digital Transformation', pillar: 'Growth' },
        { title: 'Education', pillar: 'Development' },
        { title: 'Healthcare', pillar: 'Development' },
        { title: 'Community Service', pillar: 'Development' },
        { title: 'Culture & Arts', pillar: 'Development' },
        { title: 'Youth Excellence', pillar: 'Development' },
        { title: 'International Relations & Diplomacy', pillar: 'Sustainability' },
        { title: 'Sustainability & Environment', pillar: 'Sustainability' },
        { title: 'Infrastructure & Construction', pillar: 'Sustainability' },
        { title: 'Development & Human Progress', pillar: 'Sustainability' },
        { title: 'Media & Communication', pillar: 'Sustainability' },
        { title: 'Lifetime Achievement & Legacy', pillar: 'Sustainability' },
        { title: 'Global Leadership', pillar: 'Sustainability' },
      ],
    },
    partnerships: {
      sponsorship: 'Sponsorship',
      partnerWithExcellence: 'Partner With Excellence',
      alignBrand: 'Align your brand with the UAE\'s most prestigious business awards. Connect with industry leaders and showcase your commitment to excellence.',
      investmentTiers: 'Investment Tiers',
      partnershipOptions: 'Partnership Options',
      premierTier: 'Premier Tier',
      goldPartner: 'Gold Partner',
      silverPartner: 'Silver Partner',
      bronzePartner: 'Bronze Partner',
      redCarpetPartner: 'Red-Carpet Partner',
      expressInterest: 'Express Interest',
      partnershipInquiry: 'Partnership Inquiry',
      questionsAbout: 'Questions about partnerships?',
      contactTeam: 'Contact our team →',
      benefits: {
        premierLogo: 'Premier logo placement',
        vipTable10: 'VIP table for 10 guests',
        speakingOpp: 'Speaking opportunity',
        mediaCoverage: 'Media coverage priority',
        exclusiveNetworking: 'Exclusive networking access',
        prominentLogo: 'Prominent logo placement',
        table8: 'Table for 8 guests',
        brandVisibility: 'Brand visibility',
        mediaMentions: 'Media mentions',
        networkingAccess: 'Networking access',
        logoPlacement: 'Logo placement',
        table6: 'Table for 6 guests',
        eventMaterials: 'Event materials',
        socialMention: 'Social media mention',
        logoMaterials: 'Logo on materials',
        vipInvitations2: '2 VIP invitations',
        brandAck: 'Brand acknowledgment',
      },
    },
    gala: {
      saveTheDate: 'Save the Date',
      awardsGalaNight: 'Awards Gala Night',
      theEvening: 'The Evening',
      exclusiveBlackTie: 'An Exclusive Black-Tie Celebration',
      galaDescription: 'The ONE UAE International Business Awards Gala brings together distinguished leaders, innovators, and visionaries from across the Emirates. This prestigious evening celebrates the extraordinary achievements of individuals and organizations who embody the spirit of excellence.',
      date: 'Date',
      venue: 'Venue',
      time: 'Time',
      guests: 'Guests',
      timeValue: '6:00 PM onwards',
      guestsValue: '750+',
      schedule: 'Schedule',
      programFlow: 'Program Flow',
      reception: 'Reception & Networking',
      opening: 'Opening Ceremony',
      awards: 'Award Presentations',
      dinner: 'Gala Dinner',
      location: 'Location',
      venueTitle: 'Venue',
      mainBallroom: 'Main Ballroom',
      venueAddress: 'Zabeel Ladies Club',
      dubaiUAE: 'Dubai, United Arab Emirates',
      attire: 'Attire',
      dressCode: 'Dress Code',
      blackTieNational: 'Black Tie / National Dress',
      formalAttire: 'Formal evening attire required',
      traditionalWelcome: 'Traditional national dress welcome',
      joinUs: 'Join Us',
      bePartOf: 'Be Part of the Celebration',
      submitOrPartner: 'Submit your nomination or become a partner to join us at this prestigious event.',
      submitNomination: 'Submit Nomination',
      becomePartner: 'Become a Partner',
    },
    contact: {
      getInTouch: 'Get in Touch',
      contactTitle: 'Contact',
      awardsSecretariat: 'Awards Secretariat',
      email: 'Email',
      phone: 'Phone',
      locationLabel: 'Location',
      officeHours: 'Office Hours',
      officeHoursValue: 'Sunday - Thursday, 9AM - 6PM GST',
      dedicatedTeam: 'Our team is dedicated to ensuring your experience with the ONE UAE International Business Awards is exceptional.',
      question: 'Have questions?',
    },
    nominate: {
      nominationsOpen: 'Nominations Open',
      submitYourNomination: 'Submit Your Nomination',
      recognizeExceptional: 'Recognize exceptional achievements and contributions shaping the UAE\'s future.',
      eligibility: {
        individualsOrgs: 'Individuals & Organizations',
        individualsOrgsDesc: 'Open to individuals, businesses, and institutions operating in the UAE.',
        documented: 'Documented Achievements',
        documentedDesc: 'Must demonstrate measurable impact and verified accomplishments.',
        excellence: 'Excellence Standards',
        excellenceDesc: 'Contributions aligned with UAE Vision 2071.',
      },
      application: 'Application',
      nominationForm: 'Nomination Form',
      theProcess: 'The Process',
      whatHappensNext: 'What Happens Next?',
      steps: {
        reviewed: 'Application Reviewed',
        reviewedDesc: 'Our panel reviews each submission',
        contacted: 'Nominees Contacted',
        contactedDesc: 'Selected nominees are notified',
        selection: 'Final Selection',
        selectionDesc: 'Winners revealed at Gala Night',
        celebrated: 'Winners Celebrated',
        celebratedDesc: 'Recognition with trophy presentation',
      },
      needHelp: 'Need Help?',
      helpDesc: 'Our team is available to assist with your nomination.',
      viewAllCategories: 'View All Categories',
      contactUs: 'Contact Us',
      questions: 'Questions?',
      contactAt: 'Contact us at',
    },
    program: {
      label: 'The Evening',
      title: 'Program Flow',
      reception: 'Reception & Networking',
      opening: 'Opening Ceremony',
      awards: 'Award Presentations',
      dinner: 'Gala Dinner',
      viewDetails: 'View Gala Details',
      dateLabel: 'Date',
      venueLabel: 'Venue',
      formatLabel: 'Format',
      attendeesLabel: 'Attendees',
      format: 'Ceremony + Gala Dinner',
      attendees: '750 Distinguished Guests',
    },
    audience: {
      label: 'Who Attends',
      title: 'Distinguished Guests',
      list: [
        'Government Representatives',
        'Business Leaders',
        'Entrepreneurs',
        'Healthcare Leaders',
        'Media Figures',
        'Finance Executives',
        'Tech Innovators',
      ],
    },
    partnership: {
      label: 'Partner With Us',
      title: 'Become a Sponsor',
      description: 'Join prestigious brands in supporting the UAE\'s premier business awards ceremony.',
      explore: 'Explore Partnerships',
    },
    footer: {
      explore: 'Explore',
      contact: 'Contact',
      patronageLabel: 'Under the distinguished patronage of',
      copyright: '© {year} ONE UAE International Business Awards',
    },
    social: {
      share: 'Share',
      shareOn: 'Share on {platform}',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      about: 'عن الجائزة',
      categories: 'الفئات',
      partnerships: 'الشراكات',
      gala: 'الحفل',
      contact: 'تواصل معنا',
      nominate: 'ترشيح',
      submitNomination: 'قدم ترشيحك',
    },
    hero: {
      title: 'جوائز الإمارات',
      titleAccent: 'الموحدة',
      tagline: 'جوائز الأعمال الدولية',
      patronage: 'تحت رعاية سعادة الشيخ سلطان بن ناصر بن حميد النعيمي',
      date: '٥ فبراير ٢٠٢٦',
      venue: 'نادي الزعبيل للسيدات، دبي',
      submitNomination: 'قدم ترشيحك',
      learnMore: 'اكتشف المزيد',
      addToCalendar: 'أضف إلى التقويم',
    },
    stats: {
      guests: 'ضيوف مميزون',
      categories: 'فئات الجوائز',
      dignitaries: 'كبار الشخصيات',
      night: 'ليلة استثنائية',
    },
    about: {
      label: 'عن الجوائز',
      title: 'منصة وطنية للتميز',
      description: 'جوائز الإمارات الموحدة للأعمال الدولية هي منصة وطنية مرموقة تكرم الأفراد والمؤسسات الذين يقودون مسيرة النمو والتطوير والاستدامة في دولة الإمارات.',
      date: '٥ فبراير ٢٠٢٦',
      galaLabel: 'حفل الليلة الكبرى',
      venueTitle: 'نادي الزعبيل للسيدات',
      venueDetail: 'القاعة الرئيسية، دبي',
      discoverStory: 'اكتشف قصتنا',
      intro: 'ما بدأ كرؤية لتكريم المساهمات المتميزة نما ليصبح منصة تحتفي بالإنجازات المتنوعة التي تحدد روح الوحدة والرؤية والتميز في الإمارات.',
      awardCategories: 'فئات الجوائز',
      distinguishedGuests: 'ضيوف مميزون',
      mission: 'الرسالة',
      missionText: 'تكريم القادة والمؤسسات الذين يساهمون في التقدم الوطني ورؤية الإمارات 2071.',
      vision: 'الرؤية',
      visionText: 'بناء تقليد مرموق لتكريم التميز والوحدة والتقدم المستدام.',
      underPatronage: 'تحت الرعاية',
      patronName: 'سعادة الشيخ سلطان بن ناصر بن حميد النعيمي',
      patronDesc: 'تتشرف جوائز الإمارات الموحدة للأعمال الدولية بالعمل تحت الرعاية الكريمة لسعادة الشيخ سلطان بن ناصر بن حميد النعيمي، الذي يلهمنا التزامه بالتميز والتنمية الوطنية.',
      theJourney: 'المسيرة',
      selectionProcess: 'عملية الاختيار',
      step1Title: 'الترشيح',
      step1Desc: 'يقدم الأفراد والمنظمات ترشيحات تسلط الضوء على الإنجازات الاستثنائية.',
      step2Title: 'مراجعة الخبراء',
      step2Desc: 'تقوم لجنة متميزة بتقييم الترشيحات بناءً على التأثير والابتكار.',
      step3Title: 'الاختيار النهائي',
      step3Desc: 'يتم اختيار الفائزين وتكريمهم في حفلنا السنوي المرموق.',
      submitYourNomination: 'قدم ترشيحك',
    },
    categories: {
      label: '١٨ فئة',
      title: 'فئات الجوائز',
      viewAll: 'عرض الكل',
      more: '+ ١٢ فئة إضافية',
      recognition: 'التقدير',
      categoriesOfExcellence: 'فئات التميز',
      readyToApply: 'هل أنت مستعد للتقديم؟',
      submitYourNomination: 'قدم ترشيحك',
      recognizeExcellence: 'اعترف بالتميز في مؤسستك أو رشح قائداً يستحق.',
      startNomination: 'ابدأ الترشيح',
      growth: 'النمو',
      development: 'التطوير',
      sustainability: 'الاستدامة',
      list: [
        'النمو والتميز الاقتصادي',
        'ريادة الأعمال والابتكار',
        'القيادة المؤسسية',
        'المالية والمصارف',
        'التجزئة والضيافة',
        'التكنولوجيا والرقمنة',
      ],
      fullList: [
        { title: 'النمو والتميز الاقتصادي', pillar: 'النمو' },
        { title: 'ريادة الأعمال والابتكار', pillar: 'النمو' },
        { title: 'القيادة المؤسسية', pillar: 'النمو' },
        { title: 'المالية والمصارف', pillar: 'النمو' },
        { title: 'التجزئة والضيافة', pillar: 'النمو' },
        { title: 'التكنولوجيا والتحول الرقمي', pillar: 'النمو' },
        { title: 'التعليم', pillar: 'التطوير' },
        { title: 'الرعاية الصحية', pillar: 'التطوير' },
        { title: 'خدمة المجتمع', pillar: 'التطوير' },
        { title: 'الثقافة والفنون', pillar: 'التطوير' },
        { title: 'تميز الشباب', pillar: 'التطوير' },
        { title: 'العلاقات الدولية والدبلوماسية', pillar: 'الاستدامة' },
        { title: 'الاستدامة والبيئة', pillar: 'الاستدامة' },
        { title: 'البنية التحتية والبناء', pillar: 'الاستدامة' },
        { title: 'التنمية والتقدم البشري', pillar: 'الاستدامة' },
        { title: 'الإعلام والتواصل', pillar: 'الاستدامة' },
        { title: 'الإنجاز مدى الحياة والإرث', pillar: 'الاستدامة' },
        { title: 'القيادة العالمية', pillar: 'الاستدامة' },
      ],
    },
    partnerships: {
      sponsorship: 'الرعاية',
      partnerWithExcellence: 'شارك في التميز',
      alignBrand: 'اربط علامتك التجارية بأرقى جوائز الأعمال في الإمارات. تواصل مع قادة الصناعة وأظهر التزامك بالتميز.',
      investmentTiers: 'مستويات الاستثمار',
      partnershipOptions: 'خيارات الشراكة',
      premierTier: 'المستوى الأعلى',
      goldPartner: 'شريك ذهبي',
      silverPartner: 'شريك فضي',
      bronzePartner: 'شريك برونزي',
      redCarpetPartner: 'شريك السجادة الحمراء',
      expressInterest: 'أبدِ اهتمامك',
      partnershipInquiry: 'استفسار الشراكة',
      questionsAbout: 'أسئلة حول الشراكات؟',
      contactTeam: 'تواصل مع فريقنا ←',
      benefits: {
        premierLogo: 'وضع الشعار في المقدمة',
        vipTable10: 'طاولة VIP لـ 10 ضيوف',
        speakingOpp: 'فرصة للحديث',
        mediaCoverage: 'أولوية التغطية الإعلامية',
        exclusiveNetworking: 'وصول حصري للتواصل',
        prominentLogo: 'وضع بارز للشعار',
        table8: 'طاولة لـ 8 ضيوف',
        brandVisibility: 'ظهور العلامة التجارية',
        mediaMentions: 'ذكر إعلامي',
        networkingAccess: 'وصول للتواصل',
        logoPlacement: 'وضع الشعار',
        table6: 'طاولة لـ 6 ضيوف',
        eventMaterials: 'مواد الحدث',
        socialMention: 'ذكر على وسائل التواصل',
        logoMaterials: 'الشعار على المواد',
        vipInvitations2: 'دعوتان VIP',
        brandAck: 'الاعتراف بالعلامة التجارية',
      },
    },
    gala: {
      saveTheDate: 'احفظ التاريخ',
      awardsGalaNight: 'ليلة حفل الجوائز',
      theEvening: 'الأمسية',
      exclusiveBlackTie: 'احتفال حصري بزي رسمي',
      galaDescription: 'يجمع حفل جوائز الإمارات الموحدة للأعمال الدولية القادة والمبتكرين وأصحاب الرؤى المتميزين من جميع أنحاء الإمارات. تحتفي هذه الأمسية المرموقة بالإنجازات الاستثنائية للأفراد والمنظمات الذين يجسدون روح التميز.',
      date: 'التاريخ',
      venue: 'المكان',
      time: 'الوقت',
      guests: 'الضيوف',
      timeValue: 'من الساعة 6 مساءً',
      guestsValue: '+٧٥٠',
      schedule: 'الجدول',
      programFlow: 'برنامج الحفل',
      reception: 'الاستقبال والتواصل',
      opening: 'حفل الافتتاح',
      awards: 'تقديم الجوائز',
      dinner: 'عشاء الحفل',
      location: 'الموقع',
      venueTitle: 'المكان',
      mainBallroom: 'القاعة الرئيسية',
      venueAddress: 'نادي الزعبيل للسيدات',
      dubaiUAE: 'دبي، الإمارات العربية المتحدة',
      attire: 'الملابس',
      dressCode: 'الزي الرسمي',
      blackTieNational: 'زي رسمي / زي وطني',
      formalAttire: 'يلزم ارتداء زي مسائي رسمي',
      traditionalWelcome: 'الزي الوطني التقليدي مرحب به',
      joinUs: 'انضم إلينا',
      bePartOf: 'كن جزءاً من الاحتفال',
      submitOrPartner: 'قدم ترشيحك أو كن شريكاً لتنضم إلينا في هذا الحدث المرموق.',
      submitNomination: 'قدم ترشيحك',
      becomePartner: 'كن شريكاً',
    },
    contact: {
      getInTouch: 'تواصل معنا',
      contactTitle: 'اتصل بنا',
      awardsSecretariat: 'أمانة الجوائز',
      email: 'البريد الإلكتروني',
      phone: 'الهاتف',
      locationLabel: 'الموقع',
      officeHours: 'ساعات العمل',
      officeHoursValue: 'الأحد - الخميس، 9 صباحاً - 6 مساءً بتوقيت الخليج',
      dedicatedTeam: 'فريقنا ملتزم بضمان تجربة استثنائية لك مع جوائز الإمارات الموحدة للأعمال الدولية.',
      question: 'هل لديك أسئلة؟',
    },
    nominate: {
      nominationsOpen: 'الترشيحات مفتوحة',
      submitYourNomination: 'قدم ترشيحك',
      recognizeExceptional: 'اعترف بالإنجازات والمساهمات الاستثنائية التي تشكل مستقبل الإمارات.',
      eligibility: {
        individualsOrgs: 'أفراد ومؤسسات',
        individualsOrgsDesc: 'مفتوح للأفراد والشركات والمؤسسات العاملة في الإمارات.',
        documented: 'إنجازات موثقة',
        documentedDesc: 'يجب إثبات تأثير قابل للقياس وإنجازات موثقة.',
        excellence: 'معايير التميز',
        excellenceDesc: 'مساهمات متوافقة مع رؤية الإمارات 2071.',
      },
      application: 'التقديم',
      nominationForm: 'نموذج الترشيح',
      theProcess: 'العملية',
      whatHappensNext: 'ماذا بعد؟',
      steps: {
        reviewed: 'مراجعة الطلب',
        reviewedDesc: 'تراجع لجنتنا كل طلب',
        contacted: 'التواصل مع المرشحين',
        contactedDesc: 'يتم إخطار المرشحين المختارين',
        selection: 'الاختيار النهائي',
        selectionDesc: 'الإعلان عن الفائزين في ليلة الحفل',
        celebrated: 'تكريم الفائزين',
        celebratedDesc: 'التقدير مع تقديم الكأس',
      },
      needHelp: 'تحتاج مساعدة؟',
      helpDesc: 'فريقنا متاح لمساعدتك في ترشيحك.',
      viewAllCategories: 'عرض جميع الفئات',
      contactUs: 'تواصل معنا',
      questions: 'أسئلة؟',
      contactAt: 'تواصل معنا على',
    },
    program: {
      label: 'الأمسية',
      title: 'برنامج الحفل',
      reception: 'الاستقبال والتواصل',
      opening: 'حفل الافتتاح',
      awards: 'تقديم الجوائز',
      dinner: 'عشاء الحفل',
      viewDetails: 'تفاصيل الحفل',
      dateLabel: 'التاريخ',
      venueLabel: 'المكان',
      formatLabel: 'الشكل',
      attendeesLabel: 'الحضور',
      format: 'حفل + عشاء فاخر',
      attendees: '٧٥٠ ضيفاً مميزاً',
    },
    audience: {
      label: 'من يحضر',
      title: 'الضيوف المميزون',
      list: [
        'ممثلو الحكومة',
        'قادة الأعمال',
        'رواد الأعمال',
        'قادة الرعاية الصحية',
        'شخصيات إعلامية',
        'التنفيذيون الماليون',
        'المبتكرون التقنيون',
      ],
    },
    partnership: {
      label: 'شاركنا',
      title: 'كن راعياً',
      description: 'انضم إلى العلامات التجارية المرموقة في دعم حفل جوائز الأعمال الأبرز في الإمارات.',
      explore: 'استكشف الشراكات',
    },
    footer: {
      explore: 'استكشف',
      contact: 'تواصل',
      patronageLabel: 'تحت الرعاية الكريمة لـ',
      copyright: '© {year} جوائز الإمارات الموحدة للأعمال الدولية',
    },
    social: {
      share: 'مشاركة',
      shareOn: 'مشاركة على {platform}',
    },
  },
};
